# Generated by Django 5.1.3 on 2024-12-03 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrewInCharge',
            fields=[
                ('crew_id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('leader_fn', models.CharField(max_length=255)),
                ('leader_ln', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('train_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=255)),
                ('max_speed', models.PositiveIntegerField()),
                ('no_of_seats', models.PositiveIntegerField()),
                ('no_of_toilets', models.PositiveIntegerField()),
                ('has_reclining_seats', models.BooleanField(default=False)),
                ('has_folding_tables', models.BooleanField(default=False)),
                ('has_disability_access', models.BooleanField(default=False)),
                ('has_luggage_storage', models.BooleanField(default=False)),
                ('has_vending_machines', models.BooleanField(default=False)),
                ('has_food_service', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceHistory',
            fields=[
                ('maintenance_id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('task', models.CharField(max_length=255)),
                ('condition', models.CharField(choices=[('Excellent', 'Excellent'), ('Very Good', 'Very Good'), ('Good', 'Good'), ('Bad', 'Bad'), ('Very Bad', 'Very Bad'), ('Unsatisfactory', 'Unsatisfactory')], max_length=20)),
                ('date_maintained', models.DateField()),
                ('crew', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maintenance.crewincharge')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.train')),
            ],
        ),
    ]
